version: '3.4'

services:
#For authorization service
  auth_server:
    platform: linux/amd64
    container_name: auth_server
    build:
      context: auth_service
      dockerfile: ./Dockerfile
    image: auth_service
    volumes:
      - ./auth_service/:/src
    env_file:
      - ./auth_service/.env
    ports:
      - 8081:8081
    depends_on:
      - auth_db

  auth_db:
    platform: linux/amd64
    image: postgres
    container_name: auth_db
    restart: always
    env_file:
      - ./auth_service/.env
    ports:
      - "5432:5432"


#For crypto and wallet microservices
  ganache:
    image: trufflesuite/ganache-cli
    container_name: ganache
    command: bash "npm install -g ganache && ganache-cli --host 0.0.0.0"
    restart: always
    ports:
      - "8545:8545"
  crypto_database:
    image: mongo
    container_name: crypto_database
    restart: always
    ports:
      - "27017:27017"
  crypto_server:
    image: ${DOCKER_REGISTRY-}crypto_server
    container_name: crypto_server
    build:
      context: crypto
      dockerfile: ./Crypto.Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "DatabaseSettings:ConnectionString=mongodb://crypto_database:27017"
      - "BlockchainConnections:Ganache=http://ganache:8545"
      - "SmartContractSettings:TokenAddress=0x3963ECb0ad3e0DDCde48a2f753C8fc7599197Bb9"
    depends_on:
      - crypto_database
      - ganache
      - wallets_server
    ports:
      - "5227:80"
        
  wallets_server:
    image: ${DOCKER_REGISTRY-}wallets_server
    container_name: wallets_server
    build:
      context: crypto
      dockerfile: ./Wallets.Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "DatabaseSettings:ConnectionString=mongodb://crypto_database:27017"
      - "BlockchainConnections:Ganache=http://ganache:8545"
      - "SmartContractSettings:TokenAddress=0x3963ECb0ad3e0DDCde48a2f753C8fc7599197Bb9"
    depends_on:
      - crypto_database
      - ganache
    ports:
      - "6227:80"

  lot_server:
    platform: linux/amd64
    container_name: lot_server
    build:
      context: lot_service
      dockerfile: ./Dockerfile
    image: ${DOCKER_REGISTRY-}lot_service
    depends_on:
      - auth_db
    volumes:
      - ./lot_service/:/app
      - .:/lot_service
    ports:
      - 8000:8000